version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "python manage.py a_db_connection && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - ./mysql_db:/var/lib/mysql
    restart: on-failure
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./client:/usr/share/nginx/html/frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#  telegram:
#    image: aiogram/telegram-bot-api
#    ports:
#      - "8081:8081"
#    container_name: 'telegram_bot_service'
#    restart:
#    environment:
#      - TELEGRAM_API_ID=''
#      - TELEGRAM_API_HASH=''
#    volumes:
#      - .telegram-bot-api-data:/var/lib/telegram-bot-api
