# Generated by Django 4.1.3 on 2022-12-01 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.qr_code.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UA', 'Ukraine')], max_length=30)),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('street_number', models.IntegerField()),
                ('zipcode', models.IntegerField()),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='PublicPlaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('working_time_start', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('([01]?[0-9]|2[0-3]):[0-5][0-9]')])),
                ('working_time_end', models.CharField(blank=True, max_length=5, verbose_name=django.core.validators.RegexValidator('([01]?[0-9]|2[0-3]):[0-5][0-9]'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'public_place',
            },
        ),
        migrations.CreateModel(
            name='QrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_url', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to=apps.qr_code.services.save_qr_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qr_code.publicplacemodel')),
            ],
            options={
                'db_table': 'qr_code',
            },
        ),
    ]
