# Generated by Django 4.1.3 on 2022-11-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplacemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='public_place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qr_code.publicplacemodel'),
        ),
    ]
