# Generated by Django 4.1.3 on 2022-11-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publicplacemodel',
            table='public_place',
        ),
    ]
