# Generated by Django 4.1.3 on 2022-12-01 22:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='publicplacemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrmodel',
            name='public_place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qr_code.publicplacemodel'),
        ),
    ]
