# Generated by Django 4.1.3 on 2022-12-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0003_remove_qrmodel_id_alter_publicplacemodel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicplacemodel',
            old_name='owner',
            new_name='user',
        ),
    ]
