# Generated by Django 4.1.3 on 2022-11-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_code', '0003_alter_publicplacemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplacemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicplacemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
