# Generated by Django 4.1.3 on 2022-11-30 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0004_alter_publicplacemodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicplacemodel',
            name='working_time_end',
            field=models.CharField(blank=True, max_length=5, verbose_name=django.core.validators.RegexValidator('([01]?[0-9]|2[0-3]):[0-5][0-9]')),
        ),
        migrations.AlterField(
            model_name='publicplacemodel',
            name='working_time_start',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('([01]?[0-9]|2[0-3]):[0-5][0-9]')]),
        ),
    ]
