# Generated by Django 4.1.4 on 2022-12-21 13:39

from django.db import migrations, models

import apps.qr_code.services


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0004_rename_owner_publicplacemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplacemodel',
            name='place_picture',
            field=models.ImageField(blank=True, upload_to=apps.qr_code.services.save_place_pic_to),
        ),
    ]
