# Generated by Django 4.1.5 on 2023-01-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0005_publicplacemodel_place_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='zipcode',
        ),
    ]
