# Generated by Django 4.1.3 on 2022-12-01 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_review', models.TextField(max_length=1000)),
                ('place_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('customer_name', models.CharField(max_length=64)),
                ('customer_phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('(?=.*\\+[0-9]{3}\\s?[0-9]{2}\\s?[0-9]{3}\\s?[0-9]{4}$)')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='public_place', to='qr_code.publicplacemodel')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
