# Generated by Django 4.1.4 on 2022-12-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0004_rename_owner_publicplacemodel_user'),
        ('reviews', '0002_alter_reviewmodel_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_place', to='qr_code.publicplacemodel'),
        ),
    ]
