# Generated by Django 4.1.4 on 2022-12-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtokenkey',
            name='token_key',
            field=models.CharField(default='CyzwFh-aLj2_-5BCUu7cmw', max_length=64),
        ),
    ]
