# Generated by Django 4.1.5 on 2023-01-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_alter_telegramtokenkey_token_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtokenkey',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramtokenkey',
            name='user_chat_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramtokenkey',
            name='token_key',
            field=models.CharField(default='Lq11qqokGNzs7Dhq9_GCkQ', max_length=64),
        ),
    ]
