# Generated by Django 4.1.5 on 2023-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_telegramtokenkey_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtokenkey',
            name='token_key',
            field=models.CharField(default='Xqgm-lZgMwubZIHliNeGUQ', max_length=64),
        ),
    ]
