# Generated by Django 4.1.5 on 2023-01-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_alter_telegramtokenkey_token_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtokenkey',
            name='telegram_user_nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='telegramtokenkey',
            name='token_key',
            field=models.CharField(default='5l19ZGZq7bLBHX9N7u1snA', max_length=64),
        ),
    ]
