# Generated by Django 4.1.5 on 2023-01-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0006_telegramtokenkey_telegram_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtokenkey',
            name='token_key',
            field=models.CharField(default='5C6IoHiGElboUEfvLxbISg', max_length=64),
        ),
    ]
